<?php

use App\Controllers\AuthController;
use App\Controllers\BackupController;
use App\Controllers\DashboardController;
use App\Controllers\HomeController;
use App\Controllers\InventoryController;
use App\Controllers\IsoAdminController;
use App\Controllers\IsoController;
use App\Controllers\KvmController;
use App\Controllers\LogsController;
use App\Controllers\RuntimeController;
use App\Controllers\ServerController;
use App\Controllers\SettingsController;
use App\Controllers\SsoKvmController;
use App\Controllers\UserController;

$router->get('/', [HomeController::class, 'index']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'authenticate']);
$router->get('/two-factor', [AuthController::class, 'twoFactor']);
$router->post('/two-factor', [AuthController::class, 'verifyTwoFactor']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->get('/dashboard', [DashboardController::class, 'page'])->middleware('auth');
$router->get('/servers', [ServerController::class, 'page'])->middleware('auth');
$router->get('/server', [ServerController::class, 'show'])->middleware('auth');
$router->get('/servers/status', [ServerController::class, 'status'])->middleware('auth');
$router->get('/server/webui-check', [ServerController::class, 'webUiCheck'])->middleware('auth');
$router->post('/server/power', [ServerController::class, 'power'])->middleware('auth');
$router->get('/servers/edit', [ServerController::class, 'edit'])->middleware('admin');
$router->post('/servers/create', [ServerController::class, 'create'])->middleware('admin');
$router->post('/servers/update', [ServerController::class, 'update'])->middleware('admin');
$router->post('/servers/delete', [ServerController::class, 'delete'])->middleware('admin');
$router->post('/servers/rotate-token', [ServerController::class, 'rotateToken'])->middleware('admin');
$router->post('/server/ips/add', [ServerController::class, 'addIp'])->middleware('admin');
$router->post('/server/ips/delete', [ServerController::class, 'deleteIp'])->middleware('admin');
$router->post('/server/bootdev', [ServerController::class, 'bootdev'])->middleware('admin');
$router->post('/server/bmc-reset', [ServerController::class, 'bmcReset'])->middleware('admin');
$router->get('/server/ipmi-users', [ServerController::class, 'ipmiUsers'])->middleware('admin');
$router->post('/server/ipmi-users/create', [ServerController::class, 'createIpmiUser'])->middleware('admin');
$router->post('/server/ipmi-users/delete', [ServerController::class, 'deleteIpmiUser'])->middleware('admin');
$router->post('/servers/bulk-power', [ServerController::class, 'bulkPower'])->middleware('admin');
$router->get('/api/search', [ServerController::class, 'search'])->middleware('auth');
$router->get('/isos', [IsoController::class, 'page'])->middleware('auth');
$router->post('/isos/mount', [IsoController::class, 'mount'])->middleware('auth');
$router->post('/isos/unmount', [IsoController::class, 'unmount'])->middleware('auth');
$router->post('/isos/refresh', [IsoController::class, 'refresh'])->middleware('auth');
$router->get('/iso-admin', [IsoAdminController::class, 'index'])->middleware('admin');
$router->post('/iso-admin/store', [IsoAdminController::class, 'store'])->middleware('admin');
$router->post('/iso-admin/queue-download', [IsoAdminController::class, 'queueDownload'])->middleware('admin');
$router->post('/iso-admin/update', [IsoAdminController::class, 'update'])->middleware('admin');
$router->post('/iso-admin/delete', [IsoAdminController::class, 'delete'])->middleware('admin');
$router->get('/users', [UserController::class, 'index'])->middleware('admin');
$router->get('/users/edit', [UserController::class, 'edit'])->middleware('admin');
$router->get('/users/assignments', [UserController::class, 'assignments'])->middleware('admin');
$router->post('/users/create', [UserController::class, 'create'])->middleware('admin');
$router->post('/users/update', [UserController::class, 'update'])->middleware('admin');
$router->post('/users/assignments/save', [UserController::class, 'saveAssignments'])->middleware('admin');
$router->post('/users/delete', [UserController::class, 'delete'])->middleware('admin');
$router->get('/settings', [SettingsController::class, 'index'])->middleware('admin');
$router->get('/logs', [LogsController::class, 'index'])->middleware('admin');
$router->get('/inventory', [InventoryController::class, 'index'])->middleware('admin');
$router->get('/backup', [BackupController::class, 'index'])->middleware('admin');
$router->post('/backup/run', [BackupController::class, 'run'])->middleware('admin');
$router->get('/backup/download', [BackupController::class, 'download'])->middleware('admin');
$router->post('/backup/delete', [BackupController::class, 'delete'])->middleware('admin');
$router->post('/backup/settings', [BackupController::class, 'saveSettings'])->middleware('admin');
$router->post('/settings/update', [SettingsController::class, 'update'])->middleware('admin');
$router->get('/kvm/open', [KvmController::class, 'open'])->middleware('auth');
$router->match(['GET', 'POST'], '/runtime/ipmi-kvm', [RuntimeController::class, 'ipmiKvm'])->middleware('auth');
$router->match(['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], '/runtime/bmc-proxy', [RuntimeController::class, 'bmcProxy'])->middleware('auth');
$router->get('/runtime/sso-kvm', [SsoKvmController::class, 'open']);
$router->get('/health', fn () => ['status' => 'ok', 'app' => APP_NAME, 'version' => APP_VERSION]);
$router->get('/api/me', [AuthController::class, 'me']);
$router->get('/api/dashboard/summary', [DashboardController::class, 'summary'])->middleware('auth');
$router->get('/api/servers', [ServerController::class, 'index'])->middleware('auth');
$router->get('/api/isos', [IsoController::class, 'index'])->middleware('auth');
